version: "3.5"
services:
        prometheus:
                image: prom/prometheus:v2.12.0
                restart: unless-stopped
                container_name: prometheus
                command:
                        - '--config.file=/etc/prometheus/prometheus.yml'
                        - '--storage.tsdb.path=/prometheus'
                        - '--storage.tsdb.retention.time=180d'
                        - '--storage.tsdb.retention.size=200GB'
                        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
                        - '--web.console.templates=/usr/share/prometheus/consoles'
                        - '--web.enable-lifecycle'
                ports:
                        - 9090:9090
                networks:
                        - public
                volumes:
                        - ./data:/prometheus
                        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        traefik:
                image: traefik:v1.7.16-alpine
                restart: unless-stopped
                ports:
                        - 80:80
                        - 443:443
                networks:
                        - public
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ./traefik.toml:/traefik.toml
                container_name: traefik
        qbittorrent_oauthproxy:
                image: quay.io/pusher/oauth2_proxy:v4.0.0-amd64
                container_name: qbittorrent_oauthproxy
                restart: unless-stopped
                command: "--upstream=http://qbittorrent:8080 --authenticated-emails-file=/emails.list --http-address=0.0.0.0:4180"
                volumes:
                        - emails.list:/emails.list
                depends_on:
                        - qbittorrent
                        - traefik
                networks:
                        - public
                environment:
                        - "OAUTH2_PROXY_CLIENT_ID=random_string.apps.googleusercontent.com"
                        - "OAUTH2_PROXY_CLIENT_SECRET=s3cretstuff"
                        - "OAUTH2_PROXY_COOKIE_SECRET=c00kie"
                labels:
                        - "traefik.docker.network=public"
                        - "traefik.enable=true"
                        - "traefik.basic.frontend.rule=Host:qbittorrent.example.com"
                        - "traefik.basic.port=4180"
                        - "traefik.basic.protocol=http"
                        - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:max-age=15552000"
        qbittorrent-exporter:
                container_name: qbittorrent-exporter
                image: lkollenberger/qbittorrent-exporter:2.0.0-dev
                depends_on:
                        - prometheus
                        - qbittorrent
                restart: unless-stopped
                volumes:
                        - ./qbt-exporter-settings.json:/qbt-exporter-settings.json:ro
                networks:
                        - public
        qbittorrent:
                container_name: qbittorrent
                image: linuxserver/qbittorrent:amd64-4.1.7.99201908140017-6718-e98f44aubuntu18.04.1-ls41
                environment:
                        - "TZ=America/Argentina/Buenos_Aires"
                        - "PGID=1000"
                        - "PUID=1000"
                        - "WEBUI_PORT=8080"
                hostname: "qbittorrent"
                restart: unless-stopped
                ports:
                        - 55678:55678/tcp
                        - 55678:55678/udp
                volumes:
                        - /data/download:/download
                networks:
                        - public
networks:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: "198.19.252.1/24"
